version: "2"  
services:  
  web:  
    image: nginx:latest  
    ports:  
      - "80:80" 
    restart: always
    volumes:  
      - ./app:/www/web
      - ./services/web/nginx/conf:/etc/nginx
      - ./services/web/nginx/logs:/www/web_logs
    networks:
        - code-network
    depends_on:
      - php
  mysql:  
    image: mysql:5.7 
    volumes:  
      - ./db/mysql/data:/var/lib/mysql 
      - ./db/mysql/log:/var/log/mysql
      - ./db/mysql/example_db:/var/example_db 
      - ./fecshop-2.x-example-data:/var/example_db_2.x      
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=fecshopxfd3ffaads123456
      - MYSQL_DATABASE=fecshop
    networks:
      - code-network 
  php:  
    build: 
      context: ./services/php/docker/
    restart: always
    volumes:  
      - ./app:/www/web
      - ./services/php/etc/php7.1.13.ini:/usr/local/etc/php/conf.d/php7.1.13.ini
    depends_on:
      - mongodb
      - mysql
    networks:
        - code-network  
  mongodb:
    image: mongo:3.7
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./db/mongodb/data:/data/db
      - ./db/mongodb/example_db:/data/example_db
      - ./db/mongodb/logs:/data/logs
    networks:
      - code-network 
  
  xunsearch:
    image: hightman/xunsearch:latest
    restart: always
    volumes:
      - ./db/xunsearch/data:/usr/local/xunsearch/data  
    networks:
      - code-network
  redis:
    image: redis:4.0
    restart: always
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-password
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    volumes:
      - ./db/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf 
      - ./db/redis/data:/data 
      - ./db/redis/etc/redis-password:/run/secrets/redis-password 
    networks:
      - code-network 
networks:
  code-network:
    driver: bridge
        
        
        
        
        
